import { Inter, Monoton, Comfortaa } from 'next/font/google'
import '../styles/globals.css'
import '../styles/system.scss'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })
const monoton = Monoton({ subsets: ['latin'], weight: '400', display:'swap', variable:'--font-monoton' })
const comfortaa = Comfortaa({ subsets: ['latin'], weight: '400', display:'swap', variable:'--font-comfortaa' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, monoton.variable, comfortaa.variable)}>{children}</body>
    </html>
  )
}
