import { Inter, Monoton, Comfortaa } from 'next/font/google';
import '../styles/globals.css';
import '../styles/system.scss';
import clsx from 'clsx';
import Header from '@/components/Header';
import { GlobalProvider } from '@/hooks/useGlobalData';
import Modal from '@/components/Modal';

const inter = Inter({ subsets: ['latin'] });
const monoton = Monoton({
	subsets: ['latin'],
	weight: '400',
	display: 'swap',
	variable: '--font-monoton',
});
const comfortaa = Comfortaa({
	subsets: ['latin'],
	weight: '400',
	display: 'swap',
	variable: '--font-comfortaa',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={clsx(inter.className, monoton.variable, comfortaa.variable)}
			>
				<GlobalProvider>
					<Header />
					<main>{children}</main>
					<Modal />
				</GlobalProvider>
			</body>
		</html>
	);
}
